---
title: "Перечень вопросов и заданий к экзамену"
format: html
---

# Перечень вопросов и заданий

## Анализ точечных паттернов и кластеризация

1.  Что такое точечный паттерн?
2.  Какие виды точечных паттернов есть?
3.  Основные виды пространственных эффектов точечного процесса.
4.  Основные подходы к анализу точечных паттернов.
5.  В чем разница между глобальной и локальной плотностью?
6.  Анализ точечных паттернов на основе плотности.
7.  Анализ точечных паттернов на основе расстояния между наблюдениями.
8.  Оценка локальной плотности на основе квадрантов.
9.  Ядерная оценка плотности.
10. Анализ ближайших соседей.
11. $k$-функция и ее вариации.
12. Что такое кластеризация?
13. Иерархические методы кластеризации.
14. Разделительные методы кластеризации.
15. Кластеризация на основе плотности.

## Гравитационные модели

1.  Первый закон географии.
2.  Что такое затухание расстояния?
3.  Что такое сжатие пространства и времени?
4.  На чем основаны гравитационные модели?
5.  Гравитационная модель Хаффа.
6.  Какие есть гравитационные модели?
7.  Как применяются гравитационные модели?
8.  От чего зависит вероятность использования сервиса в гравитационной модели Хаффа?
9.  

## Пространственные веса и пространственная автокорреляция

1.  Что такое пространственные веса?
2.  Методы расчета пространственных весов.
3.  Основное применение пространственных весов.
4.  Что такое пространственная автокорреляция?
5.  В чем разница между глобальной и локальной пространственной автокорреляцией?
6.  Что такое пространственный лаг?
7.  Кластеры, выявляемые при расчете локальной пространственной автокорреляции.
8.  Графическая интерпретация индекса Морана.
9.  

## Пространственная регрессия

# List of exam questions and tasks

## Point pattern analysis and clusterisation

1.  What is point pattern?
2.  Name types of point patterns.
3.  Main types of spatial effects in point process.
4.  Main approaches in point pattern analysis.
5.  Difference between global and local spatial density.
6.  Density based point pattern analysis.
7.  Distance based point pattern analysis.
8.  Quadrant local density estimation.
9.  Kernel density estimation.
10. Nearest neighbour analysis.
11. $k$-function and its variations.
12. What is clusterisation?
13. Hierarchical clusterisation methods.
14. Partitioning clusterisation methods.
15. Density based clusterisation methods.

## Gravity models

1.  First law of geography.
2.  What is distance decay?
3.  What is time-space compression?
4.  Foundation for gravity models.
5.  Huff's gravity model.
6.  What types of gravity models exist?
7.  How gravity models can be applied?
8.  In Huff's model, what parameters does probability depend on?
9.  

## Spatial weights and spatial autocorrelation

1.  What are spatial weights?
2.  Spatial weights calculation methods.
3.  Main application of spatial weights.
4.  What is spatial autocorrelation?
5.  Difference between global and local spatial autocorrelation?
6.  What is spatial lag?
7.  Clusters calculated through local spatial autocorrelation.
8.  Moran graph.

## Spatial regression
