---
title: "Домашнее задание"
format: html
number-sections: false
---

В рамках домашнего задания вам нужно выбрать набор данных, построить для него матрицу пространственных весов и протестировать датасет на пространственную автокорреляцию.

В качестве исходных данных вы можете взять любой датасет: ваш собственный, чей-то готовый (например, [отсюда](https://geodacenter.github.io/data-and-lab/)) или синтетический. Выбор исходных данных полностью за вами.

::: callout-warning
**Нельзя пользоваться набором данных, который был на занятиях. Такие работы приняты не будут.**
:::

Что необходимо сделать в работе и отобразить в отчете:

-   что за набор данных вы использовали, кратко его описать;

-   визуализировать на карте переменную, которую вы будете тестировать на пространственную автокорреляцию;

-   построить матрицу весов (можно несколько с последующим сравнением и выбором одной из них);

-   параметры матрицы весов: гистограмма, карта связности, граф связности;

-   рассчитать глобальную пространственную автокорреляцию (индекс Морана);

-   рассчитать локальню пространственную автокорреляцию и построить кластеры по ее результатам;

-   проанализировать и проинтерпретировать результаты тестирования на пространственную автокорреляцию.

::: callout-important
В этой работе самый важный этап - последний. Интерпретация ваших результатов должна быть приведена в работе обязательно.

Вы должны постараться объяснить полученные результаты и чем они могут быть объяснены. Это не значит, что вы должны точно угадать причины, вы можете просто высказать свою гипотезу/предположение, почему вы получили именно такие значения и с чем это может быть связано.
:::

При необходимости для интерпретации вы можете использовать дополнительные данные.

Отчет может быть написан в свободной форме.

Отчет в формате pdf или doc можно загрузить по [ссылке](https://forms.yandex.ru/u/67f62f93eb61460820aa1a3b/).

Срок сдачи: до 18 мая включительно.
